# Generated by Django 3.1.8 on 2021-12-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=100)),
                ('currentStep', models.IntegerField(default=0)),
                ('totalStep', models.IntegerField(default=0)),
                ('totalErrorCount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
