# Generated by Django 3.1.8 on 2021-12-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0002_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=100)),
                ('externalIpAddress', models.CharField(max_length=100)),
                ('master', models.BooleanField(default=False)),
                ('matrices', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('jobs', models.CharField(max_length=100)),
                ('alerts', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('recommendedServiceUnits', models.IntegerField(default=0)),
                ('allocatedServiceUnits', models.IntegerField(default=0)),
                ('serviceUnitStatus', models.CharField(max_length=100)),
                ('serviceUnitStatusMessage', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Instances',
            },
        ),
    ]
