# Generated by Django 3.1.8 on 2021-12-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0005_auto_20211228_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
