# Generated by Django 3.1.8 on 2021-12-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0006_instances_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instances',
            name='type',
        ),
    ]
