# Generated by Django 3.1.8 on 2021-12-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0007_remove_instances_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
