# Generated by Django 3.1.8 on 2021-12-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0008_jobs_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsonFilesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='templates/themes/files/')),
            ],
        ),
        migrations.CreateModel(
            name='personData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_type', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=100)),
            ],
        ),
    ]
