# Generated by Django 3.1.8 on 2021-12-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0009_jsonfilesdata_persondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jsonFilesData',
        ),
        migrations.AddField(
            model_name='persondata',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persondata',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persondata',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='templates/themes/files/'),
        ),
        migrations.AddField(
            model_name='persondata',
            name='realm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='grant_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='scope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
