# Generated by Django 3.1.8 on 2021-12-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0010_auto_20211231_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondata',
            old_name='files',
            new_name='template_query',
        ),
        migrations.AddField(
            model_name='persondata',
            name='adminPassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persondata',
            name='written_query',
            field=models.FileField(blank=True, null=True, upload_to='templates/themes/files/'),
        ),
    ]
