# Generated by Django 3.1.8 on 2022-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0012_jobs_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
