# Generated by Django 3.1.8 on 2022-01-12 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0013_auto_20220110_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dueDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
