# Generated by Django 3.1.8 on 2021-12-24 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions_name', models.CharField(max_length=100)),
                ('regions_ref', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenants_name', models.CharField(max_length=100)),
                ('tenants_ref', models.CharField(max_length=100)),
                ('regionz', models.ManyToManyField(to='gms.Regions')),
            ],
            options={
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persission', models.BooleanField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NameSpaces',
            fields=[
                ('namespaces_name', models.CharField(max_length=100)),
                ('namespaces_ref', models.CharField(max_length=100)),
                ('files', models.FileField(blank=True, null=True, upload_to='templates/themes/files/')),
                ('fileurl', models.URLField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantz', models.ManyToManyField(to='gms.Tenants')),
            ],
            options={
                'verbose_name_plural': 'NameSpaces',
            },
        ),
        migrations.CreateModel(
            name='integerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gms.regions')),
            ],
        ),
    ]
