# Generated by Django 3.1.8 on 2021-12-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='persission',
            new_name='permission',
        ),
    ]
