# Generated by Django 3.1.8 on 2022-01-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0002_auto_20211224_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='integertable',
            name='Access_KEY',
            field=models.CharField(blank=True, choices=[('AKIASP6I3H4VJMQDGZHG', 'AK')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='integertable',
            name='Acess_Secret_key',
            field=models.CharField(blank=True, choices=[('uOwZp0GyHWFTrdZhnbb/6HZcrorwNnRKn6TDZfR3', 'ASK')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='integertable',
            name='END_POINT',
            field=models.CharField(blank=True, choices=[('https://elasticbeanstalk-us-east-2-171683036970.s3.us-east-2.amazonaws.com/', 'EP')], max_length=100, null=True),
        ),
    ]
