# Generated by Django 3.1.8 on 2022-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0004_auto_20220109_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='integertable',
            name='Attach_bucket',
            field=models.CharField(default='elasticbeanstalk-us-east-2-171683036970', max_length=100, null=True),
        ),
    ]
